### PR TITLE
Rosbridge server details should be exposed as parameters

### PR DESCRIPTION
**Pull request by aaronsnoswell**
This PR addresses #4, #5 and #6.

### CODE REVIEW

**Comment by aaronsnoswell** [comment]
Just pushed some more changes to this PR - general readme tidying up, and added some warnings for unimplemented message converters. To see how the new method of specifying server details works, have a look at the [Readme on my fork](https://github.com/aaronsnoswell/ROSIntegration/blob/rosbridge-server-details/README.md).

**Comment by Sanic** [comment]
Hi @aaronsnoswell ,

thank you very much for your comprehensive PR. I just tested it on my setup on UE 4.18.2 and it worked very well. The configuration of the server is now way nicer than before and a more comprehensive README is always good.

**Comment by aaronsnoswell** [comment]
Glad to hear :) I'm working on integrating point clouds with this plugin so I can view them in UE4.

**Comment by aaronsnoswell** [comment]
I should have a few more PRs for you over the next few days.

**Comment by Sanic** [comment]
Hi @aaronsnoswell 
I'm looking forward to your PRs!

**Pull request merged**
