### PR TITLE
Porting to UE 4.23 

### PR DESCRIPTION
**Pull request by luigifreda**
- fixed bugs with smart pointer management (in Topic and Service classes)
- added checks in object deallocations (in private implementation classes)
- wrapped the private implementation of ROSIntegrationCore inside UObject

### CODE REVIEW

**Comment by Sanic** [comment]
Hi!
Thanks for the PR.
Is this expected to run stable on UE4 versions below 4.23?

**Comment by luigifreda** [comment]
Hi,
I basically fixed some memory management bugs without recurring to any new specific function/method of UE 4.23. I've also tested the changes on 4.22. Given this, I expect the code works on versions below 4.22 too.

**Comment by Sanic** [comment]
Cool. Thanks for the PR again and good luck with your research endeavours .

**Comment by luigifreda** [comment]
Thank you for this great project!

**Pull request merged**
