### PR TITLE
Queued publishers

### PR DESCRIPTION
**Pull request by Hemofektik**
This change allows sending ROS messages asynchronously to the rosbridge_server. This is especially handy for bigger messages such as images because sending data no longer freezes the main thread. An optional QueueSize can be specified to limit the memory consumption of queued messages and prevent message congestion.

### CODE REVIEW

**Comment by Hemofektik** [comment]
Hello, anyone there?

**Comment by Sanic** [comment]
Hi @Hemofektik ,

thanks for your PR and this nice feature proposition.
I reviewed your changes and the only thing that keeps me from merging this PR yet are the edits in the rosbridge2cpp code. This piece of code should not rely on any Unreal library functionality, as it is implemented as a pure C++11 lib (besides the dependencies on bson/json).
Do you think that you can implemented the same functionality without Unreal-specific Code in the rosbrdige2cpp core?

**Comment by Hemofektik** [comment]
Sorry, I assumed the rosbridge part is now open to include UE4 parts, since it is a hard copy of the real project and not a submodule or something similar. Additionally a UE4 specific change snuck in with my previous PR. The change in ROSBridge::UnregisterTopicCallback i made only works with the UE4 ROSIntegration as I mentioned there with a comment.

Since this PR I made a few other changes to the ROSBridge. They can all be implemented using C++11 only. I just don't know when I can do that. I let you know.
Thanks.

**Comment by Hemofektik** [comment]
Ok, I did it. Unfortunately I had to include all the other changes I made the last few weeks as well.
That includes Topics can be subscribed via blueprints and the autoreconnect feature (risbridge can restart or connection can be interrupted without problems).

**Comment by Sanic** [comment]
Hi! 
Thanks for the PR. I'll merge it.

Two notes for reference:
  - Upgrading to this new version of ROSIntegration makes it necessary to get the ROSIntegrationCore by rosinst->ROSIntegrationCore instead of rosinst->_ric ! I'll update the VisionActor to comply with these changes
  - The commits introduced a bigger lag in the VisionActor every time the images will be sent. This is a future TODO.

**Comment by Hemofektik** [comment]
Many Thanks for merging everything.
The lag is probably due to the default queue size of 10. If you reduce it to 1 the latency should be minimized.

**Pull request merged**
