### PR TITLE
Adding more BP topic types

### PR DESCRIPTION
**Pull request by phuicy**
I have implemented more of the BP features.

image

I will do more. But this is what I need for the moment.

### CODE REVIEW

**Comment by Sanic** [comment]
Hi @phuicy 
Thank you very much for the BP. Adding types is always highly appreciated.
Based on the title of your PR, i wondered about the changes in the ROSIntegrationGameInstance and the TCPConnection core functionality.
What is the rationale behind these changes?

**Comment by phuicy** [comment]
Sorry yes, commit: 7798308a was meant to be cherry picked out for #181.

I will remove that from this branch now.

**Comment by phuicy** [comment]
@Sanic Resolved.

**Comment by Sanic** [comment]
@phuicy Great! Thank you very much.

**Comment by tsender** [comment]
@phuicy How did you get this to compile? I'm using UE4.26 and I get a compile error saying "Type 'double' is not supported by blueprint." from the `void OnFloat64Message(const double& Data)` function you added in RI/Topic.h.  I'm guessing you're using UE5?

I've tried putting the UFUNCTION inside a preprocessor directive that checks to see if we are using UE5, but UE does not allow UFUNCTIONS to be placed inside preprocessor directives. I'm thinking we need to remove the `OnFloat64Message` function.

**Pull request merged**
